services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=article_management
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
#      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8080"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=article_management
    ports:
      - "5433:5432"