server:
  port: 8081

spring:
  application:
    name: demo-mini-project-001

  datasource:
    url: jdbc:postgresql://localhost:5432/article_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}

  jwt:
    secret: mK7fQ2YpR9vT4nH1cW8xD3sL6aP0uG5jB2rV8kM1tF4zN7yC9qE6wJ0hA3dS5
    expiration: 86400000 # 24 hours in milliseconds
    refresh-expiration: 604800000 # 7 days in milliseconds

#logging:
#  level:
#    com.example.demominiproject001: DEBUG
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics
